version: '3.1'

services:

  db:
    image: postgres:11
    ports:
    - 5432:5432
    volumes:
    - ./database/postgres:/data/postgres
    environment:
      POSTGRES_PASSWORD: qwerty
      POSTGRES_USER: postgres
      PGDATA : /data/postgres
      POSTGRES_DB: app-db

